
task_lister:
    pattern: /task/taskList/{idList}
    defaults: {_controller: AppBundle:Task:lister }
task_ajouter:
    pattern: /task/taskList/{idList}/ajouter/
    defaults: {_controller: AppBundle:Task:ajouter }
task_modifier:
    pattern: /task/taskList/{idList}/modifier/{id}
    defaults: {_controller: AppBundle:Task:modifier }
task_modifier_nom:
    pattern: /task/taskList/{idList}/modifierNom/{id}
    defaults: {_controller: AppBundle:Task:modifierNom }
task_supprimer:
    pattern: /task/taskList/{idList}/supprimer/{id}
    defaults: {_controller: AppBundle:Task:supprimer }



taskList_lister:
    pattern: /taskList/
    defaults: {_controller: AppBundle:TaskList:lister }
taskList_ajouter:
    pattern: /taskList/ajouter
    defaults: {_controller: AppBundle:TaskList:ajouter }
taskListe_modifier:
    pattern: /taskList/modifier/{id}
    defaults: {_controller: AppBundle:TaskList:modifier }
taskList_supprimer:
    pattern: /taskList/supprimer/{id}
    defaults: {_controller: AppBundle:TaskList:supprimer }

oauth_test:
    pattern: /oauth/
    defaults: {_controller: AppBundle:OAuth:test }


