_welcome:
    path:     /
    defaults: { _controller: AppBundle:Welcome:index }

task_lister:
    pattern: /task/
    defaults: {_controller: AppBundle:Task:lister }
task_ajouter:
    pattern: /task/ajouter
    defaults: {_controller: AppBundle:Task:ajouter }
task_modifier:
    pattern: /task/modifier/{id}
    defaults: {_controller: AppBundle:Task:modifier }
task_supprimer:
    pattern: /task/supprimer/{id}
    defaults: {_controller: AppBundle:Task:supprimer }



taskList_lister:
    pattern: /taskList/
    defaults: {_controller: AppBundle:TaskList:lister }
taskList_ajouter:
    pattern: /taskList/ajouter
    defaults: {_controller: AppBundle:TaskList:ajouter }
taskListe_modifier:
    pattern: /taskList/modifier/{id}
    defaults: {_controller: AppBundle:TaskList:modifier }
taskList_supprimer:
    pattern: /taskList/supprimer/{id}
    defaults: {_controller: AppBundle:TaskList:supprimer }


